FROM docker.io/techarchitect/berth-agent-base:latest

RUN chmod +x /usr/bin/docker-compose && \
    mkdir -p /usr/local/lib/docker/cli-plugins && \
    ln -sf /usr/bin/docker-compose /usr/local/lib/docker/cli-plugins/docker-compose

ARG GO_VERSION=1.25.5
RUN curl -sSL https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz | tar -C /usr/local -xzf -
ENV PATH="/usr/local/go/bin:/root/go/bin:${PATH}"

RUN go install github.com/air-verse/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

CMD ["air", "-c", ".air.toml"]
